# PostgresSQL container for testing purpose only

version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - "127.0.0.1:5433:5432"
    expose:
      - 5433
    environment:
      POSTGRES_PASSWORD: root # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: films # The PostgreSQL default database (automatically created at first launch)