networks:
  network:
    name: ${NETWORK_NAME}
    driver: bridge

services:
  postgres:
    image: ${POSTGRES_IMAGE}
    container_name: postgres
    hostname: postgres
    expose:
      - "${POSTGRES_PORT}"
    ports:
      - "${LOCAL_PORT}:${POSTGRES_PORT}"
    networks:
      - network
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PG_DATA: "/var/lib/postgresql/pgdata"
    volumes:
      - "postgres_data:/var/lib/postgresql/pgdata"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  init-container:
    image: mlops-demo/init-container:1.0
    build: stack/prerequisite/setupbox
    container_name: prerequisite-init
    networks:
      - network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: