# This file is used for self-managed DBT, it should be mapped to a .env file for credentials

dbt_testing:

  target: dev

  outputs:
  
    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: root
      dbname: athlete
      schema: athlete