on:
    pull_request:
        types:
            - opened
        branches:
            - dev
            - main
jobs:
    check_mlflow:
            name: check MlFlow
            runs-on: ubuntu-18.04
            steps:
                - name: greetings
                  shell: bash
                  run:  echo "Hello world !"
                - name: deploy
                  shell: bash
                  run: ./deploy.sh configs/local_docker.env mlflow
