# Configuration for connection mysql_to_postgres_films
definition_type: connection
resource_name: "mysql_to_postgres_films"
source_configuration_path: sources/mysql_films/configuration.yaml
destination_configuration_path: destinations/postgres_films/configuration.yaml

# EDIT THE CONFIGURATION BELOW!
configuration:
  status: active # REQUIRED | string | Allowed values: active, inactive, deprecated
  skip_reset: false # OPTIONAL | boolean | Flag to check if the connection should be reset after a connection update
  namespace_definition: source # OPTIONAL | string | Allowed values: source, destination, customformat
  namespace_format: "${SOURCE_NAMESPACE}" # OPTIONAL | string | Used when namespaceDefinition is 'customformat'. If blank then behaves like namespaceDefinition = 'destination'. If "${SOURCE_NAMESPACE}" then behaves like namespaceDefinition = 'source'.
  prefix: "" # REQUIRED | Prefix that will be prepended to the name of each stream when it is written to the destination
  resource_requirements: # OPTIONAL | object | Resource requirements to run workers (blank for unbounded allocations)
    cpu_limit: "" # OPTIONAL
    cpu_request: "" # OPTIONAL
    memory_limit: "" # OPTIONAL
    memory_request: "" # OPTIONAL
  schedule_type: manual # OPTIONAL | string | Allowed values: basic, cron, manual
  ## !!!! -------- PERSONNAL REMARK : impossible to pass any argument without error to schedule data, need to comment it -------- 
  #schedule_data: # OPTIONAL | object
  basic_schedule:
    time_unit: hours # REQUIRED | string | Allowed values: minutes, hours, days, weeks, months
    units: 1 # REQUIRED | integer
    # cron:
    #   cron_time_zone: "UTC" # REQUIRED | string
    #   cron_expression: "* */2 * * * ?" # REQUIRED | string
  operations:
  ## -------- Uncomment and edit the block below if you want to enable Airbyte normalization --------
    - name: "Normalization"
      operator_configuration:
        normalization:
          option: "basic"
        operator_type: "normalization"
  ## -------- Uncomment and edit the block below if you want to declare a custom transformation --------
    - name: "My DBT films transformations" # REQUIRED | string
      operator_configuration:
        dbt:
          dbt_arguments: "run --profiles-dir ./.dbt" # REQUIRED | string | Entrypoint arguments for dbt cli to run the project
          docker_image: "fishtownanalytics/dbt:0.19.1" # REQUIRED | string | Docker image URL with dbt installed
          git_repo_branch: "1-create-demo-for-dbt" # OPTIONAL | string | Git branch name
          git_repo_url: "https://github.com/bomzai/mlops-demo.git" # REQUIRED | string | Git repository URL of the custom transformation project
        operator_type: dbt # REQUIRED | string | Allowed values: dbt, normalization
  sync_catalog: # OPTIONAL | object | 🚨 ONLY edit streams.config, streams.stream should not be edited as schema cannot be changed.
    streams:
      - config:
          alias_name: basics
          cursor_field: []
          destination_sync_mode: append
          primary_key:
            - - tconst
          selected: true
          suggested: true
          sync_mode: full_refresh
        stream:
          default_cursor_field: []
          json_schema:
            properties:
              endYear:
                airbyte_type: timestamp_without_timezone
                format: date-time
                type: string
              genres:
                type: string
              isAdult:
                type: boolean
              originalTitle:
                type: string
              primaryTitle:
                type: string
              runtimeMinutes:
                type: number
              startYear:
                airbyte_type: integer
                type: number
              tconst:
                type: string
              titleType:
                type: string
            type: object
          name: basics
          namespace: films
          source_defined_primary_key:
            - - tconst
          supported_sync_modes:
            - full_refresh
            - incremental
      - config:
          alias_name: ratings
          cursor_field: []
          destination_sync_mode: append
          primary_key:
            - - tconst
          selected: true
          suggested: true
          sync_mode: full_refresh
        stream:
          default_cursor_field: []
          json_schema:
            properties:
              averageRating:
                type: number
              numVotes:
                airbyte_type: integer
                type: number
              tconst:
                type: string
            type: object
          name: ratings
          namespace: films
          source_defined_primary_key:
            - - tconst
          supported_sync_modes:
            - full_refresh
            - incremental
      - config:
          alias_name: dates
          cursor_field: []
          destination_sync_mode: append
          primary_key:
            - - tconst
          selected: true
          suggested: true
          sync_mode: full_refresh
        stream:
          default_cursor_field: []
          json_schema:
            properties:
              dataInsertTime:
                format: date
                type: string
              tconst:
                type: string
            type: object
          name: dates
          namespace: films
          source_defined_primary_key:
            - - tconst
          supported_sync_modes:
            - full_refresh
            - incremental
